#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

CLUSTER_NAME=tns
BASEDIR=$(cd `dirname $0`; pwd)

API_PORT=8555
#EXPOSE=30040:30040@k3d-tns-server
EXPOSE=8080:80@loadbalancer
VOLUME=$BASEDIR/.volume

mkdir -p .volume

k3d cluster create $CLUSTER_NAME \
  --volume $VOLUME:/kubernetes \
  --volume $VOLUME/local:/opt/local-path-provisioner \
  --api-port $API_PORT \
  --port $EXPOSE \
  --kubeconfig-update-default=false

echo -n 'creating'
set +e
while ! k3d kubeconfig get $CLUSTER_NAME >/dev/null 2>&1; do
  sleep 1
  echo -n '.'
done
set -e
echo 'done'

export KUBECONFIG=$(k3d kubeconfig write $CLUSTER_NAME)
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
kubectl patch storageclass local-path -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

kubectl config use-context k3d-$CLUSTER_NAME
